### ISSUE TITLE
Non-Debian Font file paths

### ISSUE THREAD

**Issue by v4hn** [TAMS-Group/scriptpanel#1]
The font path is hardcoded to `/usr/share/fonts/liberation-fonts-ttf/LiberationMono-Bold.ttf`, but that's a Ubuntu (Debian?) convention.
They proper way to find the font [would use FontConfig](https://stackoverflow.com/questions/10542832/how-to-use-fontconfig-to-get-font-list-c-c).

**Comment by JonasTietz** [comment]
Should be fixed by 52090f1bbfee9de930810ef6f3185cefb236b25a.
