### ISSUE TITLE
text size does not scale with DPI/button height

### ISSUE THREAD

**Issue by v4hn** [TAMS-Group/scriptpanel#2]
So with displays with higher DPI or bigger buttons, the labels appear very small.

**Comment by JonasTietz** [comment]
Should be fixed by d36f9ac081ca071fe9e109d4e7fbd5f4176b6a6c.

**Comment by v4hn** [comment]
> Closed #2.

Great, Thanks!

I just pushed up two minor fix-up commits. Please test them on Ubuntu as well, but I expect they work there too.

**Comment by JonasTietz** [comment]
For me that does not work. I'm not quite sure, but I seems like there is no .cmake file in the Ubuntu package.

**Comment by lianghongzhuo** [comment]
I can compile it on ubuntu 20.04. @v4hn

**Comment by JonasTietz** [comment]
Hmm. Ok I think I identified the problem. Apparently the .cmake file for Fontconfig is in the cmake package. But only since Ubuntu 20.04. I'm runnign Ubuntu 18.04.

**Comment by lianghongzhuo** [comment]
Yes, 18.04 won't work

**Comment by v4hn** [comment]
Sorry for the hick-up, I really did not expect cmake support for Fontconfig to be *that* new...

I just pushed a fix and tested it even on 16.04.
